### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by dangminhbk** [intellisoft567/mvc567#1]
I initial project using cli. I follow instruction in documentation but got this error.
![image](https://user-images.githubusercontent.com/31243225/65374117-6ba76c80-dcb0-11e9-83db-69c1a86d7f1c.png)

**Comment by gsk567** [comment]
The issue is appeared because the cli generate empty configuration file and SmtpConfig:Port cannot be parsed becaused it is generated as empty string. Try to replace the empty string with valid int32 value like 8888. The fix will be pushed and published in the next hours.

**Comment by gsk567** [comment]
The issue is fixed and the new version of the CLI is available in NuGet.

**Comment by dangminhbk** [comment]
@gsk567 thank.
