### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by dangminhbk** [intellisoft567/mvc567#2]
At first. I follow mvc567 instruction to run app without any issues. But when I change connection string to a different database, then use comand `update-database`. It said database was updated successfully. But when i run app again, there are an unhadled exception when I navigate to admin router.
![image](https://user-images.githubusercontent.com/31243225/65959469-44a12580-e47c-11e9-9302-8e95da3fd180.png)

**Comment by gsk567** [comment]
The platform contains a default database initializer. The error you receive is based on the lack of users into the database. Be sure the initializer has been executed successfully.

**Comment by dangminhbk** [comment]
How to check default initializer has been executed ? 
> Application is configured to detect if there is non-executed migrations and will trigger the database update operation on application start.

I read document and it said that. And I also check the database and there are 2 user in database.

**Comment by dangminhbk** [comment]
https://github.com/intellisoft567/mvc567/blob/master/src/Mvc567.Components/TagHelpers/UserFullNameTagHelper.cs
`            var user = this.uow.GetStandardRepository().Get<User>(this.uow.CurrentUserId.Value);
            output.Content.SetContent($"{user.FirstName} {user.LastName}");
`
I think you should check if user is null or not.

**Comment by gsk567** [comment]
Yes, I will set a null check on the next version of the library. Unfortunately, this does not completely fix the issue. Based on the tag helper code there are two options for this error - lack of user with this Id and lack of Id in the session cookie. I will investigate where is the main reason for the problem. Thank you for the error caught. I would fix the issue as soon as possible. :)
